### PR TITLE
Wrap rewritten cookies in quotes.

### LINKED ISSUE #14: Set-Cookie header is changed when using foxy
I posted this issue to browser_sync (https://github.com/BrowserSync/browser-sync/issues/842)  first, but then I traced it to foxy.
I am using django and proxy mode in browser sync. I noticed that after using django.contrib.messages, django.contrib.sessions stopped working (I cannot login, send post request through CSRF). This is caused by django not being able to parse message cookie, and all cookies after that. After some investigation I noticed that when django is sending:
`
Set-Cookie:messages="412d773c32c6c08a1d6ddf88b24bef15a1dafd91$[[\"__json_message\"\0540\05420\054\"Cofni\\u0119to publikacj\\u0119 strony \\\"Strona G\\u0142\\u00f3wna\\\" w j\\u0119zyku Polski\"]]"; httponly; Path=/
`
foxy is passing:
`set-cookie:messages=412d773c32c6c08a1d6ddf88b24bef15a1dafd91$[[\"__json_message\"\0540\05420\054\"Cofni\\u0119to publikacj\\u0119 strony \\\"Strona G\\u0142\\u00f3wna\\\" w j\\u0119zyku Polski\"]]; Path=/; HttpOnly
`
As you can see, there are double quotes missing around actual message. Probably django is not able to parse this cookie without them.
I am using foxy like that:
```javascript
var foxy = require('foxy');
proxy = foxy('http://localhost:8001').listen(8002);
```
Also I checked that http-proxy (without foxy) is not changing these headers and is working correctly

### PR DESCRIPTION
**Pull request by emperorcezar**
Fixes #14

### CODE REVIEW

**Comment by shakyShane** [comment]
Thanks, I will jump onto this asap :)

**Comment by emperorcezar** [comment]
I updated this to move the rewriteCookies function to the config so the whole thing can be customized.

**Comment by shakyShane** [comment]
Can someone point me to a django app I can install and test this on? I have python/django already setup - so just need some sort of app with logins already set up to set this

**Comment by shakyShane** [comment]
opted for https://github.com/shakyShane/foxy/pull/16 in the end which solves this issue along with removing the cookie dep.

Thanks for your time :)

**Pull request closed without merging**
